# Generated by Django 5.0.2 on 2024-12-21 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='產品名稱')),
                ('description', models.TextField(verbose_name='產品簡介')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立日期')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_set', to='company.company', verbose_name='所屬公司')),
            ],
            options={
                'verbose_name': '產品',
                'verbose_name_plural': '產品',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/product/', verbose_name='產品圖片')),
                ('is_primary', models.BooleanField(default=False, verbose_name='是否為主要圖片')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上傳日期')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product', verbose_name='所屬產品')),
            ],
            options={
                'verbose_name': '產品圖片',
                'verbose_name_plural': '產品圖片',
            },
        ),
    ]
