# Generated by Django 5.0.2 on 2024-12-28 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('product', '0002_productcate_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcate',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_cate', to='company.company', verbose_name='所屬公司'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productcate',
            name='name',
            field=models.CharField(max_length=255, verbose_name='類別名稱'),
        ),
        migrations.AlterUniqueTogether(
            name='productcate',
            unique_together={('company', 'name')},
        ),
        migrations.AddIndex(
            model_name='productcate',
            index=models.Index(fields=['company', 'name'], name='product_pro_company_5ee78c_idx'),
        ),
    ]
