# Generated by Django 5.0.2 on 2024-12-19 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Graduate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.TextField(default='國立高雄科技大學智慧商務系')),
                ('grade', models.CharField(max_length=20)),
                ('student_id', models.TextField(default='000000000')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('priority', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('home_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('mobile_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('address', models.TextField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('intro', models.TextField(blank=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='static/member/')),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('is_show', models.BooleanField(default=False, verbose_name='是否要展示於官網')),
                ('graduate', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='member.graduate')),
                ('private', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.position')),
            ],
        ),
        migrations.CreateModel(
            name='OutstandingAlumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievements', models.TextField(blank=True, null=True, verbose_name='傑出成就')),
                ('is_featured', models.BooleanField(default=False, verbose_name='是否展示於官網')),
                ('highlight', models.CharField(max_length=100, verbose_name='傑出事蹟摘要')),
                ('date_awarded', models.DateField(blank=True, null=True, verbose_name='授予日期')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outstanding_alumni', to='member.member')),
            ],
        ),
    ]
