# Generated by Django 5.0.2 on 2024-12-19 05:39

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('intro', ckeditor.fields.RichTextField()),
                ('info_clicks', models.IntegerField(default=0)),
                ('deadline', models.DateField()),
                ('release_date', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=True, verbose_name='是否發布')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.TextField(default='公司名稱?')),
                ('name', models.TextField()),
                ('phone', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('recruit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='recruit.recruit')),
            ],
        ),
        migrations.CreateModel(
            name='RecruitImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/recruit/')),
                ('image_type', models.CharField(choices=[('large', 'Large Image'), ('small', 'Small Image')], max_length=5)),
                ('recruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='recruit.recruit')),
            ],
        ),
    ]
