# Generated by Django 5.0.2 on 2024-12-19 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('intro', models.TextField(null=True)),
            ],
            options={
                'verbose_name': '產業列',
                'verbose_name_plural': '產業列',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='公司名稱')),
                ('positions', models.CharField(max_length=255, verbose_name='公司在職職位')),
                ('description', models.TextField(verbose_name='公司簡介')),
                ('products', models.CharField(max_length=255, verbose_name='販售商品')),
                ('product_description', models.TextField(verbose_name='販售商品簡介')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='static/company/', verbose_name='照片')),
                ('website', models.URLField(max_length=500, verbose_name='公司網站連結')),
                ('address', models.TextField(blank=True, null=True, verbose_name='公司地點')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='聯絡信箱')),
                ('clicks', models.BigIntegerField(default=0, verbose_name='點擊次數')),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='聯絡電話')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='member.member')),
                ('industry', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='industry', to='company.industry')),
            ],
            options={
                'verbose_name': '公司',
                'verbose_name_plural': '公司',
            },
        ),
    ]
